// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbgn_DjJ8qwRsw3odxfj-BG4eLdKGUPLA',
    appId: '1:552437117634:web:d60b787980db44c4cf015b',
    messagingSenderId: '552437117634',
    projectId: 'whatsapp-fc5c2',
    authDomain: 'whatsapp-fc5c2.firebaseapp.com',
    databaseURL: 'https://whatsapp-fc5c2-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-fc5c2.appspot.com',
    measurementId: 'G-G2KV5RP9RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8GVMdnxxT_kXIUdfi43BdeDhyt_sgN94',
    appId: '1:552437117634:android:a8662e5e57253557cf015b',
    messagingSenderId: '552437117634',
    projectId: 'whatsapp-fc5c2',
    databaseURL: 'https://whatsapp-fc5c2-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-fc5c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2xKBub9L-Bq9gL-dsBDx0NSkosWBvyI',
    appId: '1:552437117634:ios:0b410cadd35c32f1cf015b',
    messagingSenderId: '552437117634',
    projectId: 'whatsapp-fc5c2',
    databaseURL: 'https://whatsapp-fc5c2-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-fc5c2.appspot.com',
    androidClientId: '552437117634-bdhrhb2nvb22s4mqn5v4g12otlktq2e3.apps.googleusercontent.com',
    iosClientId: '552437117634-8fsvib9rv6o5v5d9h1i3b2h16ff6mft0.apps.googleusercontent.com',
    iosBundleId: 'com.example.getXTutorial',
  );
}
